type RefreshToken {
  token: String!
  expiration: String!
}

type AuthenticateUserResponse {
  user: User!
  refreshToken: RefreshToken!
}

type Mutation {
  authenticateUser(data: AuthenticateUserInput): AuthenticateUserResponse
}

input AuthenticateUserInput {
  email: String!
  password: String!
}
